version: 9999
resources:
    - type: node
      count: 1
      with:
        - type: memory
          count: 256
        - type: socket
          count: 2
          with:
            - type: gpu
              count: 4
            - type: slot
              count: 2
              with:
                - type: L3cache
                  count: 1
                  with:
                    - type: core
                      count: 4
                      with:
                        - type: pu
                          count: 1

# a comment
attributes:
  system:
    duration: 3600
tasks:
  - command: [ "app" ]
    slot: default
    count:
      per_slot: 1
